import Header from "@/components/Header";
import type { Metadata } from "next";
import "./globals.css";
import { getSession } from "@/lib/session";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();

  return (
    <html lang="ko">
      <body>
        <Header session={session} />
        {children}
      </body>
    </html>
  );
}